"""hrms_clean_foundation

Revision ID: e549798c86c6
Revises: 
Create Date: 2026-04-09 15:18:06.900977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e549798c86c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('hrms_members', schema=None) as batch_op:
    #    batch_op.alter_column('reports_to',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(length=36),
    #           existing_nullable=True)
    #    batch_op.alter_column('is_active',
    #           existing_type=sa.INTEGER(),
    #           type_=sa.Boolean(),
    #           nullable=True,
    #           existing_server_default=sa.text('1'))
    #    batch_op.alter_column('invited_by',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(length=36),
    #           existing_nullable=True)
    #    batch_op.drop_constraint(None, type_='foreignkey')
    #    batch_op.create_foreign_key(None, 'users', ['invited_by'], ['id'])
    #    batch_op.create_foreign_key(None, 'hrms_members', ['reports_to'], ['id'])
    #    batch_op.drop_column('updated_at')
    #    batch_op.drop_column('invites_used_this_month')
    #    batch_op.drop_column('monthly_invite_limit')
    #    batch_op.drop_column('status')
    #    batch_op.drop_column('reports_to_id')

    #with op.batch_alter_table('jobs', schema=None) as batch_op:
    #    batch_op.alter_column('assigned_hiring_manager_id',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(length=36),
    #           existing_nullable=True)
    #    batch_op.alter_column('assigned_recruiter_id',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(length=36),
    #           existing_nullable=True)
    #    batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    #with op.batch_alter_table('users', schema=None) as batch_op:
    #    batch_op.alter_column('role',
    #           existing_type=sa.VARCHAR(length=9),
    #           type_=sa.Enum('JOBSEEKER', 'RECRUITER', 'ADMIN', 'HIRING_MANAGER', name='userrole'),
    #           existing_nullable=True)

    # ### end Alembic commands ###


def upgrade() -> None:
    with op.batch_alter_table('hrms_members', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('invites_used_this_month')
        batch_op.drop_column('monthly_invite_limit')
        batch_op.drop_column('status')
        batch_op.drop_column('reports_to_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('JOBSEEKER', 'RECRUITER', 'ADMIN', 'HIRING_MANAGER', name='userrole'),
               existing_nullable=True)

#def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
#    with op.batch_alter_table('users', schema=None) as batch_op:
#        batch_op.alter_column('role',
#               existing_type=sa.Enum('JOBSEEKER', 'RECRUITER', 'ADMIN', 'HIRING_MANAGER', name='userrole'),
#               type_=sa.VARCHAR(length=9),
#               existing_nullable=True)

#    with op.batch_alter_table('jobs', schema=None) as batch_op:
#        batch_op.drop_constraint(None, type_='foreignkey')
#        batch_op.alter_column('assigned_recruiter_id',
#               existing_type=sa.String(length=36),
#               type_=sa.TEXT(),
#               existing_nullable=True)
#        batch_op.alter_column('assigned_hiring_manager_id',
#               existing_type=sa.String(length=36),
#               type_=sa.TEXT(),
#               existing_nullable=True)

#    with op.batch_alter_table('hrms_members', schema=None) as batch_op:
#        batch_op.add_column(sa.Column('reports_to_id', sa.VARCHAR(), nullable=True))
#        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=9), nullable=True))
#        batch_op.add_column(sa.Column('monthly_invite_limit', sa.INTEGER(), nullable=True))
#        batch_op.add_column(sa.Column('invites_used_this_month', sa.INTEGER(), nullable=True))
#        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
#        batch_op.drop_constraint(None, type_='foreignkey')
#        batch_op.drop_constraint(None, type_='foreignkey')
#        batch_op.create_foreign_key(None, 'hrms_members', ['reports_to_id'], ['id'])
#        batch_op.alter_column('invited_by',
#               existing_type=sa.String(length=36),
#               type_=sa.TEXT(),
#               existing_nullable=True)
#        batch_op.alter_column('is_active',
#               existing_type=sa.Boolean(),
#               type_=sa.INTEGER(),
#               nullable=False,
#               existing_server_default=sa.text('1'))
#        batch_op.alter_column('reports_to',
#               existing_type=sa.String(length=36),
#               type_=sa.TEXT(),
#               existing_nullable=True)

    # ### end Alembic commands ###

def downgrade() -> None:
    pass